export const SUPPORTED_TOOLS = {
  // --- КАТЕГОРИЯ: PDF & ДОКУМЕНТЫ ---
  'jpg-to-pdf': {
    source: 'jpg',
    target: 'pdf',
    sourceName: 'JPG',
    targetName: 'PDF',
    accept: '.jpg,.jpeg',
    maxFiles: 20,
    icon: '🖼️',
    category: 'pdf',
    description: 'Превратите ваши изображения JPG в аккуратный PDF документ.',
  },
  'png-to-pdf': {
    source: 'png',
    target: 'pdf',
    sourceName: 'PNG',
    targetName: 'PDF',
    accept: '.png',
    maxFiles: 20,
    icon: '📄',
    category: 'pdf',
    description: 'Конвертируйте рисунки PNG в PDF с сохранением прозрачности.',
  },
  'webp-to-pdf': {
    source: 'webp',
    target: 'pdf',
    sourceName: 'WebP',
    targetName: 'PDF',
    accept: '.webp',
    maxFiles: 20,
    icon: '🕸️',
    category: 'pdf',
    description: 'Соберите оптимизированные изображения WebP в один PDF файл.',
  },
  'pdf-to-jpg': {
    source: 'pdf',
    target: 'jpg',
    sourceName: 'PDF',
    targetName: 'JPG',
    accept: '.pdf',
    maxFiles: 10,
    icon: '📸',
    category: 'pdf',
    description: 'Быстрое извлечение всех страниц из PDF в формат JPG.',
  },
  'pdf-to-png': {
    source: 'pdf',
    target: 'png',
    sourceName: 'PDF',
    targetName: 'PNG',
    accept: '.pdf',
    maxFiles: 10,
    icon: '🎨',
    category: 'pdf',
    description: 'Конвертируйте страницы PDF в высококачественные PNG изображения.',
  },

  // --- КАТЕГОРИЯ: КОНВЕРТЕР ИЗОБРАЖЕНИЙ ---
  'png-to-jpg': {
    source: 'png',
    target: 'jpg',
    sourceName: 'PNG',
    targetName: 'JPG',
    accept: '.png',
    maxFiles: 30,
    icon: '🔄',
    category: 'image',
    description: 'Быстрое преобразование PNG в формат JPG сжатием веса.',
  },
  'jpg-to-png': {
    source: 'jpg',
    target: 'png',
    sourceName: 'JPG',
    targetName: 'PNG',
    accept: '.jpg,.jpeg',
    maxFiles: 30,
    icon: '💎',
    category: 'image',
    description: 'Конвертируйте JPG в PNG для добавления прозрачного фона.',
  },
  'png-to-webp': {
    source: 'png',
    target: 'webp',
    sourceName: 'PNG',
    targetName: 'WebP',
    accept: '.png',
    maxFiles: 50,
    icon: '⚡',
    category: 'image',
    description: 'Оптимизируйте ваши PNG изображения в современный формат WebP.',
  },
  'jpg-to-webp': {
    source: 'jpg',
    target: 'webp',
    sourceName: 'JPG',
    targetName: 'WebP',
    accept: '.jpg,.jpeg',
    maxFiles: 50,
    icon: '🚀',
    category: 'image',
    description: 'Сжимайте фотографии JPG в формат WebP для ускорения сайтов.',
  },
  'webp-to-jpg': {
    source: 'webp',
    target: 'jpg',
    sourceName: 'WebP',
    targetName: 'JPG',
    accept: '.webp',
    maxFiles: 40,
    icon: '🖼️',
    category: 'image',
    description: 'Преобразуйте веб-картинки WebP в стандартный формат JPG.',
  },
  'tiff-to-jpg': {
    source: 'tiff',
    target: 'jpg',
    sourceName: 'TIFF',
    targetName: 'JPG',
    accept: '.tiff,.tif',
    maxFiles: 15,
    icon: '📷',
    category: 'image',
    description: 'Конвертируйте тяжелые файлы TIFF со сжатием в JPG.',
  },
  'jpg-to-ico': {
    source: 'jpg',
    target: 'ico',
    sourceName: 'JPG',
    targetName: 'ICO',
    accept: '.jpg,.jpeg',
    maxFiles: 5,
    icon: '🎯',
    category: 'image',
    description: 'Создайте иконку favicon.ico для вашего сайта из любой картинки JPG.',
  }
};